import { NgModule } from '@angular/core';
import { HTTP_INTERCEPTORS } from '@angular/common/http';

import { EafHttpInterceptor } from '../../assets/lib/eaf-ng2-module/src/eafHttpInterceptor';
import * as ApiServiceProxies from './service-proxies';
import { DashboardServiceProxy } from './dashboard.service-proxy';
import { EditionServiceProxy } from './edition.service-proxy';
import { MassNotificationServiceProxy } from './mass-notification.service-proxy';
import { OrganizationUnitServiceProxy } from './organization-unit.service-proxy';
import { PaymentServiceProxy } from './payment.service-proxy';
import { TenantSubscriptionServiceProxy } from './tenant-subscription.service-proxy';
import { UserDelegationServiceProxy } from './user-delegation.service-proxy';

@NgModule({
  providers: [
    ApiServiceProxies.AboutServiceProxy,
    ApiServiceProxies.AccountServiceProxy,
    ApiServiceProxies.AdBreakServiceProxy,
    ApiServiceProxies.AdminBuildServiceProxy,
    ApiServiceProxies.AdminDashboardServiceProxy,
    ApiServiceProxies.AdminGameServiceProxy,
    ApiServiceProxies.AdminReportServiceProxy,
    ApiServiceProxies.AdminUserServiceProxy,
    ApiServiceProxies.AntiForgeryServiceProxy,
    ApiServiceProxies.ArbitraryUserDataServiceProxy,
    ApiServiceProxies.AuditLogServiceProxy,
    ApiServiceProxies.AuthServiceProxy,
    ApiServiceProxies.BuildValidationServiceProxy,
    ApiServiceProxies.CachingServiceProxy,
    ApiServiceProxies.CategoryServiceProxy,
    ApiServiceProxies.ChatFeatureCheckerServiceProxy,
    ApiServiceProxies.ChatServiceProxy,
    ApiServiceProxies.CloudSaveServiceProxy,
    ApiServiceProxies.CommonLookupServiceProxy,
    ApiServiceProxies.CompanyEmployeeServiceProxy,
    ApiServiceProxies.CompanyServiceProxy,
    DashboardServiceProxy,
    ApiServiceProxies.DeveloperBillingProfileServiceProxy,
    ApiServiceProxies.DeveloperDashboardServiceProxy,
    EditionServiceProxy,
    ApiServiceProxies.DeveloperEarningsServiceProxy,
    MassNotificationServiceProxy,
    OrganizationUnitServiceProxy,
    PaymentServiceProxy,
    TenantSubscriptionServiceProxy,
    UserDelegationServiceProxy,
    ApiServiceProxies.DeveloperGameServiceProxy,
    ApiServiceProxies.DeveloperProfileServiceProxy,
    ApiServiceProxies.DeveloperTeamServiceProxy,
    ApiServiceProxies.ExportsServiceProxy,
    ApiServiceProxies.ExternalResourceServiceProxy,
    ApiServiceProxies.FeatureFlagServiceProxy,
    ApiServiceProxies.FileServiceProxy,
    ApiServiceProxies.FriendshipServiceProxy,
    ApiServiceProxies.GameAssetsServiceProxy,
    ApiServiceProxies.GameBuildServiceProxy,
    ApiServiceProxies.GameBuildsServiceProxy,
    ApiServiceProxies.GameCatalogServiceProxy,
    ApiServiceProxies.GameChatServiceProxy,
    ApiServiceProxies.GameMetricsServiceProxy,
    ApiServiceProxies.GameplayServiceProxy,
    ApiServiceProxies.GamePreviewServiceProxy,
    ApiServiceProxies.GameSocialServiceProxy,
    ApiServiceProxies.GoogleServiceProxy,
    ApiServiceProxies.HealthServiceProxy,
    ApiServiceProxies.HomeServiceProxy,
    ApiServiceProxies.HostSettingsServiceProxy,
    ApiServiceProxies.InspectorServiceProxy,
    ApiServiceProxies.LanguageServiceProxy,
    ApiServiceProxies.LeaderboardServiceProxy,
    ApiServiceProxies.ModerationServiceProxy,
    ApiServiceProxies.MultiplayerServiceProxy,
    ApiServiceProxies.NotificationServiceProxy,
    ApiServiceProxies.PermissionServiceProxy,
    ApiServiceProxies.PlayerAccountServiceProxy,
    ApiServiceProxies.PlayerFeedbackAnalyticsServiceProxy,
    ApiServiceProxies.PlaytestServiceProxy,
    ApiServiceProxies.PrivacyServiceProxy,
    ApiServiceProxies.ProfileServiceProxy,
    ApiServiceProxies.RecaptchaValidatorServiceProxy,
    ApiServiceProxies.RegistrationServiceProxy,
    ApiServiceProxies.RevenueContractServiceProxy,
    ApiServiceProxies.RoleServiceProxy,
    ApiServiceProxies.SessionServiceProxy,
    ApiServiceProxies.TagServiceProxy,
    ApiServiceProxies.TenantAddressServiceProxy,
    ApiServiceProxies.TenantServiceProxy,
    ApiServiceProxies.TimingServiceProxy,
    ApiServiceProxies.TokenAuthServiceProxy,
    ApiServiceProxies.UiCustomizationSettingsServiceProxy,
    ApiServiceProxies.UserContentServiceProxy,
    ApiServiceProxies.UserLoginServiceProxy,
    ApiServiceProxies.UserReportServiceProxy,
    ApiServiceProxies.UserServiceProxy,
    ApiServiceProxies.UserTenantAssociationServiceProxy,
    ApiServiceProxies.WebhookEventServiceProxy,
    ApiServiceProxies.WebhookSendAttemptServiceProxy,
    ApiServiceProxies.WebhookSubscriptionServiceProxy,
    ApiServiceProxies.WebLogServiceProxy,
    { provide: HTTP_INTERCEPTORS, useClass: EafHttpInterceptor, multi: true },
  ],
})
export class ServiceProxyModule {}
