sonar.projectKey=eaf.projectname.ui
sonar.projectName=eaf.projectname.ui
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/node_modules/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
