<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\common.props"></Import>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>GameHub.Core</AssemblyName>
		<PackageId>GameHub.Core</PackageId>
		<UserSecretsId>Eaf-GameHub-894FDFC1-6482-4A56-926A-3C46C9FE0329</UserSecretsId>
		<RootNamespace>GameHub</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<EmbeddedResource Include="Application\Localization\GameHub\GameHub-pt-BR.xml" />
		<EmbeddedResource Include="Application\Localization\GameHub\GameHub.xml" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Eaf.Middleware.Core" Version="9.4.6" />
		<PackageReference Include="Hangfire.Console" Version="1.4.3" />
		<PackageReference Include="Abp" Version="10.5.0" />
		<PackageReference Include="Abp.ZeroCore" Version="10.5.0" />
		<PackageReference Include="Abp.AutoMapper" Version="10.5.0" />
		<PackageReference Include="AutoMapper" Version="14.0.0" />
		<PackageReference Include="Abp.AspNetCore" Version="10.5.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
	</ItemGroup>
</Project>
