using GameHub.Authentication.Dto;
using GameHub.Admin.Dto;
using GameHub.Gameplay.Dto;
using GameHub.Developer.Dto;
using GameHub.Catalog.Dto;
using GameHub.Monetization;
using System.Linq;
using System.Collections.Generic;
using System;
using System.ComponentModel.DataAnnotations;

namespace GameHub.Gameplay.Dto;

/// <summary>
/// Input to start a new play session.
/// </summary>
public class StartPlaySessionInput
{
    /// <summary>Game to play.</summary>
    [Required]
    public Guid GameId { get; set; }

    /// <summary>Player device type: "Desktop", "Mobile", "Tablet".</summary>
    [Required]
    [StringLength(20)]
    public string DeviceType { get; set; } = string.Empty;

    /// <summary>Browser user agent string.</summary>
    [StringLength(500)]
    public string Browser { get; set; }

    /// <summary>HTTP referrer that led to the game.</summary>
    [StringLength(500)]
    public string Referrer { get; set; }

    /// <summary>Origin of the player traffic.</summary>
    public TrafficSource TrafficSource { get; set; }

    /// <summary>UTM source parameter that led to the game.</summary>
    [StringLength(128)]
    public string UtmSource { get; set; }

    /// <summary>UTM medium parameter that led to the game.</summary>
    [StringLength(128)]
    public string UtmMedium { get; set; }

    /// <summary>UTM campaign parameter that led to the game.</summary>
    [StringLength(128)]
    public string UtmCampaign { get; set; }

    /// <summary>Idempotency key generated by the client to avoid duplicate play counts on retries.</summary>
    [StringLength(64)]
    public string ClientRequestId { get; set; }
}
