<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\common.props"></Import>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>GameHub.Application</AssemblyName>
		<PackageId>GameHub.Application</PackageId>
		<RootNamespace>GameHub</RootNamespace>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DocumentationFile></DocumentationFile>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\GameHub.Core\GameHub.Core.csproj" />
		<ProjectReference Include="..\GameHub.EntityFrameworkCore\GameHub.EntityFrameworkCore.csproj" />
		<PackageReference Include="Eaf.Middleware.Application" Version="9.3.0" />
	</ItemGroup>
</Project>
