version: '3.4'

services:
  eaf.gamehub.web.host:
    image: ${DOCKER_REGISTRY-}eafgamehubwebhost
    build:
      context: ../..
      dockerfile: Templates/Api/Dockerfile
    networks:
      - eaf-network

networks:
  eaf-network:
    driver: bridge
